name: Node.js CI
on: [push, pull_request]
jobs:
  build:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
#          backend/package-lock.json
    - run: |
        npm ci
        npm run build --if-present
  lint:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
#          backend/package-lock.json
    - run: |
        npm ci
        npm run build --if-present
        npm run test
